changeEmailの修正
yushi0620honda/-Deliverables pull request #21
Opened 2022-08-16 08:05 UTC by yushi0620honda

2022-08-19 17:29 UTC, ShizukaKurosawa commented
クラス名が`EmailForm`ではメールアドレスの機能に関わるクラスということは分かりますが、メールアドレスの「何をする」のに利用するクラスなのか明確ではありません。
そのため、クラス名を`ChangeEmailForm`に変更してください。

2022-08-19 17:36 UTC, ShizukaKurosawa commented
エラーメッセージについてですが、ユーザー目線ではないので、下記のように修正してください。
「新しいメールアドレス」のエラーメッセージ：新しいメールアドレスを入力してください
「新しいメールアドレスの確認」のエラーメッセージ：新しいメールアドレスと同じメールアドレスを入力してください

2022-08-19 17:37 UTC, ShizukaKurosawa requested changes

2022-08-19 17:37 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/controller/ChangeEmailController.java
> +    	int userId = (int) session.getAttribute("userId"); // !動作確認用!セッションからuserIdを取得し、userIdに再代入
インデントを揃えてください。

2022-08-19 17:37 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/domain/model/EmailForm.java
> +	private String email;
このコメントだと、第三者が見た時に分かりづらいです。
コメントを「新しいメールアドレス」、変数名は「`newEmail`」の方が良いです。
（`email`は新規登録の機能で利用されている変数名のため）

2022-08-19 17:40 UTC, ShizukaKurosawa commented
メールアドレス変更後に表示される「現在のメールアドレス」が、変更前のメールアドレスになっているので修正してください。

2022-08-21 18:47 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/controller/ChangeEmailController.java
> +    	int userId = (int) session.getAttribute("userId"); // !動作確認用!セッションからuserIdを取得し、userIdに再代入
確認しました。
ありがとうございます。

2022-08-21 18:47 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/domain/model/EmailForm.java
> +	private String email;
確認しました。
ありがとうございます。

2022-08-22 12:37 UTC, ShizukaKurosawa requested changes

2022-08-22 12:37 UTC, ShizukaKurosawa commented on src/main/resources/messages.properties
>  #\u30d1\u30b9\u30ef\u30fc\u30c9
`messages.properties`ファイルが文字化けしているので、ファイルの文字コードをUTF-8にして作成し直してください。

2022-08-22 12:37 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/domain/repository/jdbc/ChangeEmailDao.java
> +                        , userId);
インデントを揃えてください。

2022-08-22 12:37 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/controller/ChangeEmailController.java
> +		return "redirect:/changeEmail";
`changeEmail`に`redirect`していますが、意図があって`redirect`しているのですか？

2022-08-22 12:45 UTC, ShizukaKurosawa commented
動作確認してからGitに上げていますか？
バリデーションが効いてないように見えます。

2022-08-22 16:11 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/domain/repository/jdbc/ChangeEmailDao.java
> +                        , userId);
確認しました。
ありがとうございます。

2022-08-22 16:12 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/controller/ChangeEmailController.java
> +		return "redirect:/changeEmail";
新しいメールアドレスに変更後、ちゃんと機能しているか確認のためにredirectしていました。

2022-08-27 02:21 UTC, ShizukaKurosawa requested changes

2022-08-27 03:23 UTC, yushi0620honda commented on src/main/resources/messages.properties
>  #\u30d1\u30b9\u30ef\u30fc\u30c9
確認しました。
ありがとうございます。

2022-08-27 03:23 UTC, yushi0620honda commented on src/main/resources/messages.properties
> +AbstractUserDetailsAuthenticationProvider.credentialsExpired=パスワードの有効期限が切れています。
確認しました。
ありがとうございます。

2022-08-27 03:23 UTC, yushi0620honda commented on src/main/resources/messages.properties
> +AbstractUserDetailsAuthenticationProvider.expired=アカウントの有効期限が切れています。
確認しました。
ありがとうございます。

2022-08-27 03:23 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/domain/repository/jdbc/ChangeEmailDao.java
>  	@Autowired
確認しました。
ありがとうございます。

2022-08-27 03:23 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/controller/ChangeEmailController.java
>  	@PostMapping("/changeEmail")
確認しました。
ありがとうございます。

2022-08-28 09:45 UTC, ShizukaKurosawa commented
バリデーションで引っかかっているにもかかわらず、DBが`update`されていませんか？
SQLの実行タイミングを考慮して実装してください。

2022-08-29 17:07 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/controller/ChangeEmailController.java
> +		return "redirect:/changeEmail";
`redirect`を利用する場面について調べた上で、`redirect`するかどうかを判断してください。

2022-08-29 17:14 UTC, ShizukaKurosawa commented
> エラーメッセージについてですが、ユーザー目線ではないので下記のように修正してください。 「新しいメールアドレス」のエラーメッセージ：新しいメールアドレスを入力してください 「新しいメールアドレスの確認」のエラーメッセージ：新しいメールアドレスと同じメールアドレスを入力してください

新しいメールアドレスが空だった場合のエラーメッセージが修正されていないで、修正してください。

2022-09-06 12:44 UTC, ShizukaKurosawa requested changes

2022-09-06 12:44 UTC, ShizukaKurosawa commented on src/main/resources/templates/login/changeEmail.html
> +								<span class="text-danger" th:if="${#fields.hasErrors('emailEqual')}" th:errors="*{emailEqual}">email error</span>
`emailEqual`は英語としておかしいので、`equalEmail`に修正してください。

2022-09-06 12:44 UTC, ShizukaKurosawa commented on src/main/resources/messages.properties
> +Email.signupForm.email={0}にはメールアドレスを入力してください
「メールアドレスにはメールアドレスを入力してください」というエラーメッセージは、日本語としておかしいので修正してください。

2022-09-06 14:55 UTC, yushi0620honda commented on src/main/resources/templates/login/changeEmail.html
> +								<span class="text-danger" th:if="${#fields.hasErrors('emailEqual')}" th:errors="*{emailEqual}">email error</span>
確認しました。
ありがとうございます。

2022-09-06 14:55 UTC, yushi0620honda commented on src/main/resources/messages.properties
> +Email.signupForm.email={0}にはメールアドレスを入力してください
確認しました。
ありがとうございます。

2022-09-06 16:56 UTC, ShizukaKurosawa requested changes

2022-09-06 16:56 UTC, ShizukaKurosawa commented on src/main/resources/messages.properties
> +Email.signupForm.email={0}を入力してください
解体新書にも記載されていたと思いますが、`@Email`はメールアドレス形式のバリデーションがかけられます。
そのため、「メールアドレスはメールアドレス形式で入力してください」というメッセージが妥当だと思います。
何のためのバリデーションなのかを考えてエラーメッセージを記載してください。

2022-09-06 16:56 UTC, ShizukaKurosawa commented on src/main/resources/messages.properties
> +NotBlank=空になっています
「空になっています」というメッセージは、ユーザーに表示するメッセージとして不適切です。
適切なメッセージに変更してください。

2022-09-07 13:11 UTC, yushi0620honda commented on src/main/resources/messages.properties
> +NotBlank=空になっています
確認しました。
ありがとうございます。

2022-09-07 13:11 UTC, yushi0620honda commented on src/main/resources/messages.properties
> +Email.signupForm.email={0}を入力してください
確認しました。
ありがとうございます。

2022-09-09 13:50 UTC, ShizukaKurosawa requested changes

2022-09-09 13:50 UTC, ShizukaKurosawa commented on src/main/resources/messages.properties
> +NotBlank=空になっています
修正が入っていない様に見えますが、修正できていますか？

2022-09-10 14:50 UTC, yushi0620honda commented on src/main/resources/messages.properties
> +NotBlank=空になっています
確認しました。
ありがとうございます。

2022-09-10 14:54 UTC, yushi0620honda commented on src/main/resources/messages.properties
> +NotBlank=空になっています
修正しました。
ありがとうございます。

2022-09-11 08:04 UTC, ShizukaKurosawa approved these changes

2022-09-11 08:04 UTC, merged