homeの修正
yushi0620honda/-Deliverables pull request #22
Opened 2022-08-16 08:45 UTC by yushi0620honda

2022-08-19 17:45 UTC, ShizukaKurosawa requested changes

2022-08-19 17:45 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/controller/HomeController.java
> +    	int userId = (int) session.getAttribute("userId"); // !動作確認用!セッションからuserIdを取得し、userIdに再代入
インデントを揃えてください。

2022-08-21 14:52 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/controller/HomeController.java
> +    	int userId = (int) session.getAttribute("userId"); // !動作確認用!セッションからuserIdを取得し、userIdに再代入
確認しました。
ありがとうございます。

2022-08-22 12:29 UTC, ShizukaKurosawa approved these changes

2022-08-22 12:29 UTC, merged