changeContractの修正
yushi0620honda/-Deliverables pull request #23
Opened 2022-08-16 08:57 UTC by yushi0620honda

2022-09-14 11:28 UTC, ShizukaKurosawa requested changes

2022-09-14 11:28 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/controller/ChangeContractController.java
> +
インデントを揃えてください。

2022-09-14 11:28 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/controller/ChangeContractController.java
> +      return "redirect:/changeContract";
インデントを揃えてください。

2022-09-14 14:38 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/controller/ChangeContractController.java
> +
確認しました。
ありがとうございます。

2022-09-14 14:38 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/controller/ChangeContractController.java
> +      return "redirect:/changeContract";
確認しました。
ありがとうございます。

2022-09-20 19:25 UTC, ShizukaKurosawa requested changes

2022-09-23 02:25 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/controller/ChangeContractController.java
> +		return "redirect:/changeContract";
修正しました。
ありがとうございます。

2022-09-27 16:12 UTC, ShizukaKurosawa approved these changes

2022-09-27 16:12 UTC, merged