changePasswordの修正
yushi0620honda/-Deliverables pull request #24
Opened 2022-08-16 09:32 UTC by yushi0620honda

2022-08-19 18:01 UTC, ShizukaKurosawa requested changes

2022-08-21 14:47 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/controller/ChangePasswordController.java
> +    	String newPassword = passwordEncoder.encode(passwordForm.getNewPassword());
確認しました。
ありがとうございます。

2022-08-22 12:27 UTC, ShizukaKurosawa requested changes

2022-08-22 12:27 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/controller/ChangePasswordController.java
> +		return "redirect:/changePassword";
`changePassword`に`redirect`していますが、意図があって`redirect`しているのですか？

2022-08-22 16:13 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/controller/ChangePasswordController.java
> +		return "redirect:/changePassword";
新しいパスワードに変更後、ちゃんと機能しているか確認のためにredirectしていました。

2022-08-23 12:42 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/controller/ChangePasswordController.java
> +		return "redirect:/changePassword";
動作確認をするために`redirect`にしたということは、今後HTMLを返すよう変更する可能性があるということですか？
結論を言うと、今回の場合は`redirect`は不要です。
パスワードが更新された後に更新完了メッセージを出さないのであれば、ユーザー視点で見てもHTMLのページをそのまま返してあげる方が良いです。
また、`redirect`がどんな場面で利用されるのか明確にできていないようなので、調べてチェックリスト記載しておいてください。

2022-08-29 17:22 UTC, ShizukaKurosawa commented
現在のパスワードが一致しない場合でも`password`の`update`が実行されています。
動作確認をして、実装（バリデーション、`update`のタイミング）を見直してください。

2022-09-09 14:01 UTC, ShizukaKurosawa requested changes

2022-09-10 14:43 UTC, yushi0620honda commented on src/main/resources/messages.properties
> +NotBlank=空になっています
確認しました。
ありがとうございます。

2022-09-10 14:43 UTC, yushi0620honda commented on src/main/resources/templates/login/changePassword.html
> +						<div class="form-group" th:classappend="${#fields.hasErrors('passwordEqual')} ?'has-error'">
確認しました。
ありがとうございます。

2022-09-11 08:03 UTC, ShizukaKurosawa requested changes

2022-09-11 08:03 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/domain/model/changePasswordForm.java
> +	public boolean isEqualPassword() {
`isEqualPassword`を利用する場合は、`isEqualToPassword`になります。

2022-09-12 14:27 UTC, yushi0620honda commented on src/main/resources/messages.properties
> +Length.changePasswordForm.currentPassword=8桁以上で入力してください
確認しました。
ありがとうございます。

2022-09-12 14:27 UTC, yushi0620honda commented on src/main/resources/messages.properties
> +Length.changePasswordForm.confirmPassword=8桁以上で入力してください
確認しました。
ありがとうございます。

2022-09-12 14:27 UTC, yushi0620honda commented on src/main/resources/messages.properties
> +Length.changePasswordForm.newPassword=8桁以上で入力してください
確認しました。
ありがとうございます。

2022-09-12 14:27 UTC, yushi0620honda commented on src/main/resources/messages.properties
> +NotBlank.changePasswordForm.confirmPassword=パスワード形式で入力してください
確認しました。
ありがとうございます。

2022-09-12 14:27 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/domain/model/changePasswordForm.java
> +	public boolean isEqualPassword() {
確認しました。
ありがとうございます。

2022-09-14 11:20 UTC, ShizukaKurosawa commented
`messages.properties`について、同ファイルの1 - 12行目のような記載方法が良いと思います。
品質の問題なので、修正するか否かは任せます。

2022-09-14 11:24 UTC, ShizukaKurosawa approved these changes

2022-09-15 12:28 UTC, merged