changeContractTimeの修正
yushi0620honda/-Deliverables pull request #25
Opened 2022-08-16 12:01 UTC by yushi0620honda

2022-08-19 18:21 UTC, ShizukaKurosawa requested changes

2022-08-19 18:21 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/domain/repository/jdbc/MonthDao.java
> +//	}
不要な実装であれば、コメントアウトではなく削除してください。

2022-08-19 18:21 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/domain/repository/jdbc/WorkTimeDao.java
> +//    }
不要な実装であれば、コメントアウトではなく削除してください。

2022-08-19 18:21 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/domain/service/MonthService.java
> +//	}
不要な実装であれば、コメントアウトではなく削除してください。

2022-08-19 18:21 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/domain/service/WorkTimeService.java
> +//	}
不要な実装であれば、コメントアウトではなく削除してください。

2022-08-19 18:21 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/controller/ChangeContractTimeController.java
> +    	//int workTimeId = workTimeService.getWorkTimeIdByMonthId(monthId);
不要な実装であれば、コメントアウトではなく削除してください。

2022-08-19 18:21 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/controller/ChangeContractTimeController.java
> +    	contractService.updateContractTime(contractForm.getContractTime(), contractForm.getStartTime(), contractForm.getBreakTime(), contractForm.getEndTime(), contractId);
引数の指定についてはもう一度確認してください。

2022-08-19 18:40 UTC, ShizukaKurosawa requested changes

2022-08-19 18:40 UTC, ShizukaKurosawa commented on src/main/resources/templates/login/changeContractTime.html
> -					<h4>契約勤務時間を変更しました</h4>
勤務時間を変更後に表示されるようにしておいた方がユーザーに親切です。
（今回の実装については、設計書に記載されていないので任意です）

2022-08-21 14:25 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/domain/repository/jdbc/MonthDao.java
> +//	}
確認しました。
ありがとうございます。

2022-08-21 14:25 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/domain/repository/jdbc/WorkTimeDao.java
> +//    }
確認しました。
ありがとうございます。

2022-08-21 14:25 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/domain/service/MonthService.java
> +//	}
確認しました。
ありがとうございます。

2022-08-21 14:25 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/domain/service/WorkTimeService.java
> +//	}
確認しました。
ありがとうございます。

2022-08-21 14:26 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/controller/ChangeContractTimeController.java
> +    	//int workTimeId = workTimeService.getWorkTimeIdByMonthId(monthId);
確認しました。
ありがとうございます。

2022-08-21 14:26 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/controller/ChangeContractTimeController.java
> +    	contractService.updateContractTime(contractForm.getContractTime(), contractForm.getStartTime(), contractForm.getBreakTime(), contractForm.getEndTime(), contractId);
確認しました。
ありがとうございます。

2022-08-21 14:26 UTC, yushi0620honda commented on src/main/resources/templates/login/changeContractTime.html
> -					<h4>契約勤務時間を変更しました</h4>
確認しました。
ありがとうございます。

2022-08-22 12:21 UTC, merged