signupの修正
yushi0620honda/-Deliverables pull request #28
Opened 2022-08-18 14:25 UTC by yushi0620honda

2022-08-19 18:53 UTC, ShizukaKurosawa commented
メールアドレスの変更・パスワードの変更の際に利用している項目名が日本語なのに対して、新規登録の項目名は英語になっている、というのは一貫性がないので統一してください。

2022-08-22 12:10 UTC, ShizukaKurosawa requested changes

2022-08-22 12:10 UTC, ShizukaKurosawa commented on src/main/resources/templates/login/signup.html
>  							<div class="form-group" th:classappend="${#fields.hasErrors('confirmPassword')} ?'has-error'">
パスワード・パスワードの確認は、テキストではなくパスワード形式で表示されるようにしてください。
以前「パスワードの変更」でも指摘しましたが、パスワードが見えてしまうのはセキュリティ的に良くありません。

2022-08-22 15:26 UTC, yushi0620honda commented on src/main/resources/templates/login/signup.html
>  							<div class="form-group" th:classappend="${#fields.hasErrors('confirmPassword')} ?'has-error'">
確認しました。
ありがとうございます。

2022-08-23 11:46 UTC, ShizukaKurosawa approved these changes

2022-08-23 12:26 UTC, ShizukaKurosawa commented
動作確認をしましたか？
申請時間が`insert`されていません。
![スクリーンショット 2022-08-23 21 13 52](https://user-images.githubusercontent.com/63050866/186157648-06e21edf-5804-4fb8-88ed-61ba106e205b.png)

2022-09-12 01:30 UTC, merged