workStatusの修正
yushi0620honda/-Deliverables pull request #30
Opened 2022-08-18 15:46 UTC by yushi0620honda

2022-08-27 02:22 UTC, ShizukaKurosawa commented
`WorkTimeDao`でエラーが吐かれていて起動できないと思いますが、起動できていますか？

2022-08-27 02:25 UTC, ShizukaKurosawa commented
`src/main/java/com/example/demo/login/domain/repository/jdbc/WorkTimeDao.java`
上記クラス名についてですが、`WorkTimeDaoJdbc`というクラス名の方がしっくりくると思います。（Daoで終わるとインターフェースと勘違いしてしまう可能性があるため）

2022-08-27 02:26 UTC, ShizukaKurosawa requested changes

2022-08-27 02:26 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/controller/MonthDetailsController.java
>      WorkTimeService workTimeService;
インデントを揃えてください。

2022-08-27 02:26 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/controller/MonthDetailsController.java
>          model.addAttribute("monthId", monthId);
インデントを揃えてください。

2022-08-27 02:26 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/controller/MonthDetailsController.java
>      	workTimeService.insertWorkTime(workTimeForm);
インデントを揃えてください。

2022-08-27 02:26 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/controller/MonthDetailsController.java
> +		return "redirect:/monthDetails/" + monthId + "/" +  contractId;
`redirect`すべきか、もう一度考慮してみてください。
可変の値を返却する場合の記載方法について、見直してみてください。

2022-08-27 02:26 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/domain/service/WorkTimeService.java
> +                if (x.getWorkDay().equals(date)) {
参考までに、この場合は変数を`x`ではなく明記した方が良いです。
第三者がこの実装を見た時に、

- `x`だとどんな変数なのか分からない
- リストだと分かったとして、どんな値が格納されているのか分からない

と言った懸念点があります。

変数`i`を用いることがありますが、`if`文で条件分岐の際に数値を比較する場合のみ利用されます。
このような意味を持たない変数はについては、利用する場所が限定されます。

2022-08-27 02:26 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/domain/service/WorkTimeService.java
>  	}
インデントを揃えてください。

2022-08-27 04:02 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/domain/service/WorkTimeService.java
>  	}
確認しました。
ありがとうございます。

2022-08-27 04:02 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/controller/MonthDetailsController.java
>      	workTimeService.insertWorkTime(workTimeForm);
確認しました。
ありがとうございます。

2022-08-27 04:02 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/controller/MonthDetailsController.java
>          model.addAttribute("monthId", monthId);
確認しました。
ありがとうございます。

2022-08-27 04:03 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/controller/MonthDetailsController.java
>      WorkTimeService workTimeService;
確認しました。
ありがとうございます。

2022-08-28 16:18 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/domain/service/WorkTimeService.java
> +                if (x.getWorkDay().equals(date)) {
確認しました。
ありがとうございます。

2022-09-12 11:40 UTC, ShizukaKurosawa requested changes

2022-09-12 11:40 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/controller/MonthDetailsController.java
> +    WorkTimeService workTimeService;
インデントを揃えてください。

2022-09-12 11:40 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/controller/MonthDetailsController.java
> +        model.addAttribute("monthId", monthId);
インデントを揃えてください。

2022-09-12 11:40 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/controller/MonthDetailsController.java
> +	@PostMapping("/monthDetails/{monthId}/{contractId}")
インデントを揃えてください。

2022-09-12 11:40 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/controller/MonthDetailsController.java
> +        return "redirect:/monthDetails/" + monthId + "/" + contractId;
インデントを揃えてください。

2022-09-12 14:15 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/controller/MonthDetailsController.java
> +        model.addAttribute("monthId", monthId);
確認しました。
ありがとうございます。

2022-09-12 14:15 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/controller/MonthDetailsController.java
> +	@PostMapping("/monthDetails/{monthId}/{contractId}")
確認しました。
ありがとうございます。

2022-09-12 14:15 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/controller/MonthDetailsController.java
> +        return "redirect:/monthDetails/" + monthId + "/" + contractId;
確認しました。
ありがとうございます。

2022-09-12 15:28 UTC, ShizukaKurosawa commented
動作確認しました。
1月の勤務詳細を表示した際に、2月の日付が表示されます。
1月の勤務詳細を選択したら1月の日付が、2月の勤務詳細を表示したら2月の日付が表示されるようにしてください。

https://user-images.githubusercontent.com/63050866/189693893-a05f66c0-fb9d-4f3b-b47a-eb8a31d6abd9.mov

2022-09-12 16:09 UTC, ShizukaKurosawa requested changes

2022-09-12 16:09 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/controller/MonthDetailsController.java
> +		return "redirect:/monthDetails/" + monthId + "/" + contractId;
redirectするべきかもう一度考慮してください。
返却するエンドポイントの記載方法について、見直してください。

2022-09-20 15:22 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/controller/MonthDetailsController.java
> +		return "redirect:/monthDetails/" + monthId + "/" +  contractId;
確認しました。
ありがとうございます。

2022-09-20 15:23 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/controller/MonthDetailsController.java
> +		return "redirect:/monthDetails/" + monthId + "/" + contractId;
確認しました。
ありがとうございます。

2022-09-28 15:30 UTC, ShizukaKurosawa commented
勤務日の削除・勤務情報の変更タブのレイアウトが気になるので、こんな感じにしてみてください。

https://user-images.githubusercontent.com/63050866/192820345-13b5df95-6a07-4a7e-8ecd-55183b69dfbc.mov

2022-10-03 14:45 UTC, merged