contractsの修正
yushi0620honda/-Deliverables pull request #33
Opened 2022-08-26 19:04 UTC by yushi0620honda

2022-08-27 02:53 UTC, ShizukaKurosawa requested changes

2022-08-27 02:53 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/controller/ContractsController.java
>  	ContractService contractService;
インデントを確認してください。

2022-08-27 02:53 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/controller/ContractsController.java
>    		model.addAttribute("contractList", contractList);
インデントを揃えてください。

2022-08-27 03:37 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/controller/ContractsController.java
>  	ContractService contractService;
確認しました。
ありがとうございます。

2022-08-27 03:37 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/controller/ContractsController.java
>    		model.addAttribute("contractList", contractList);
確認しました。
ありがとうございます。

2022-08-28 09:26 UTC, ShizukaKurosawa approved these changes

2022-08-28 09:38 UTC, ShizukaKurosawa approved these changes

2022-08-28 09:38 UTC, merged