applyDetailの修正
yushi0620honda/-Deliverables pull request #36
Opened 2022-09-11 14:38 UTC by yushi0620honda

2022-09-12 15:41 UTC, ShizukaKurosawa requested changes

2022-09-12 15:41 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/controller/ApplyDetailController.java
> +		return "redirect:/applyDetail/" + userId;
`redirect`でなくて良いのでは？
返却するエンドポイントの記載方法も見直してください。

2022-09-12 15:41 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/domain/repository/UserDao.java
> +	public void updateUserBlock(User user, int userId) throws DataAccessException;
引数に`user`と`userId`を別々に指定しているのはなぜですか？
実装を確認しないで記載していますが、`User`クラスに`userId`が定義されているのでは？

2022-09-12 15:41 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/domain/repository/jdbc/UserDaoJdbcImpl.java
>                  + " userStatus,"
インデントを揃えてください。

2022-09-12 15:41 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/domain/repository/jdbc/UserDaoJdbcImpl.java
> +				, 1
これは何の`1`ですか？

2022-09-12 15:41 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/domain/repository/jdbc/UserDaoJdbcImpl.java
> +				, 2
これは何の`2`ですか？

2022-09-12 15:41 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/domain/service/UserService.java
> +		dao.updateUserBlock(user, userId);
メソッドの引数を見直してください。

2022-09-12 15:41 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/domain/repository/jdbc/UserDaoJdbcImpl.java
> +	public void updateUserBlock(User user, int userId) throws DataAccessException {
メソッドの引数を見直してください。

2022-09-12 15:41 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/domain/repository/jdbc/UserDaoJdbcImpl.java
> +	public void updateUserStatus(User user, int userId) throws DataAccessException {
メソッドの引数を見直してください。

2022-09-12 15:41 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/controller/ApplyDetailController.java
> +		return "redirect:/applyDetail/" + userId;
`redirect`でなくて良いのでは？
返却するエンドポイントの記載方法も見直してください。

2022-09-15 14:15 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/domain/repository/UserDao.java
> +	public void updateUserBlock(User user, int userId) throws DataAccessException;
修正しました。
ありがとうございます。

2022-09-15 14:15 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/domain/repository/jdbc/UserDaoJdbcImpl.java
>                  + " userStatus,"
修正しました。
ありがとうございます。

2022-09-15 14:16 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/domain/repository/jdbc/UserDaoJdbcImpl.java
> +				, 1
userStatusを１（許可）するためです。

2022-09-15 14:16 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/domain/repository/jdbc/UserDaoJdbcImpl.java
> +				, 2
userStatusを２（拒否）するためです。

2022-09-15 14:16 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/domain/service/UserService.java
> +		dao.updateUserBlock(user, userId);
修正しました。
ありがとうございます。

2022-09-15 14:16 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/domain/repository/jdbc/UserDaoJdbcImpl.java
> +	public void updateUserBlock(User user, int userId) throws DataAccessException {
修正しました。
ありがとうございます。

2022-09-15 14:16 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/domain/repository/jdbc/UserDaoJdbcImpl.java
> +	public void updateUserStatus(User user, int userId) throws DataAccessException {
修正しました。
ありがとうございます。

2022-09-15 14:16 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/controller/ApplyDetailController.java
> +		return "redirect:/applyDetail/" + userId;
修正しました。
ありがとうございます。

2022-09-16 15:31 UTC, ShizukaKurosawa commented
設計書の画面では「申請日時」となっていますが、現在の実装は「申請時間」になっており、時間ではなく日付が表示されています。
「申請日時」が表示されるようにしてください。

2022-09-20 12:23 UTC, ShizukaKurosawa commented
レイアウト確認済ですか？
![スクリーンショット 2022-09-20 21 13 35](https://user-images.githubusercontent.com/63050866/191256579-85dd78f7-9d40-412e-a4cb-6b333e5d3b96.png)

2022-09-20 19:08 UTC, ShizukaKurosawa requested changes

2022-09-20 19:08 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/domain/repository/jdbc/UserDaoJdbcImpl.java
> +				"INSERT INTO user(userName," + " email," + " password," + " role," + " userStatus," + " requestedAt)"
SQL文を修正してください。
一行であれば、「`"INSERT INTO user(userName, email, password, role, userStatus, requestedAt)"`」で大丈夫です。

2022-09-20 19:08 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/domain/repository/jdbc/UserDaoJdbcImpl.java
> +		jdbc.update("UPDATE user" + " SET" + " userStatus = ?," + " requestedAt = ?" + " WHERE userId = ?", 1,
SQL文を修正してください。

2022-09-20 19:08 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/domain/repository/jdbc/UserDaoJdbcImpl.java
> +		jdbc.update("UPDATE user" + " SET" + " userStatus = ?," + " requestedAt = ?" + " WHERE userId = ?", 2,
SQL文を修正してください。

2022-09-21 15:53 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/domain/repository/jdbc/UserDaoJdbcImpl.java
> +				"INSERT INTO user(userName," + " email," + " password," + " role," + " userStatus," + " requestedAt)"
修正しました。
ありがとうございます。

2022-09-21 15:53 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/domain/repository/jdbc/UserDaoJdbcImpl.java
> +		jdbc.update("UPDATE user" + " SET" + " userStatus = ?," + " requestedAt = ?" + " WHERE userId = ?", 1,
修正しました。
ありがとうございます。

2022-09-21 15:53 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/domain/repository/jdbc/UserDaoJdbcImpl.java
> +		jdbc.update("UPDATE user" + " SET" + " userStatus = ?," + " requestedAt = ?" + " WHERE userId = ?", 2,
修正しました。
ありがとうございます。

2022-09-24 02:04 UTC, ShizukaKurosawa requested changes

2022-09-24 02:04 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/domain/repository/jdbc/UserDaoJdbcImpl.java
> +		List<Map<String, Object>> getList = jdbc.queryForList("SELECT * FROM user where userStatus = 0");
`WHERE`句が小文字になっていますが、大丈夫ですか？（動作確認できていますか？）

2022-09-25 15:04 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/domain/repository/jdbc/UserDaoJdbcImpl.java
> +		List<Map<String, Object>> getList = jdbc.queryForList("SELECT * FROM user where userStatus = 0");
修正しました。
動作確認はできています！
ありがとうございます。

2022-09-27 14:25 UTC, ShizukaKurosawa approved these changes

2022-09-27 14:25 UTC, merged