contractの修正
yushi0620honda/-Deliverables pull request #42
Opened 2022-09-13 16:00 UTC by yushi0620honda

## プルリク前　確認内容
- [x] インデントがずれていないか
- [x] コンフリクトが起きてないか
- [x] 動作確認をしているか
- [x] チケットの仕様を満たしているか
- [x] レイアウトは仕様通りか
- [x] Diff view　縦横確認したか
- [x] ブランチ名は正しいか

2022-09-14 10:50 UTC, ShizukaKurosawa requested changes

2022-09-14 10:50 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/controller/ContractController.java
> +	return "redirect:/contract";
27行目で`login/contract`を返しているのに対し、39行目で`redirect`しているはなぜですか？

2022-09-14 10:50 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/domain/model/ContractForm.java
> +	@NotNull(message = "想定始業時間を入力してください")
`LocalDateTime`、`LocalDate`、`LocalTime`型を宣言する場合は、`@NotNull`ではなく`@NotBlank`を利用してください。
`Null`の場合だけでなく、空文字の場合もエラーを出すようにバリデーションをかけてください。

2022-09-14 11:12 UTC, ShizukaKurosawa commented
`src/main/resources/messages.properties`の修正は今回の修正とは関係ない修正に見えますが、コミットに含まれているのはなぜですか？

2022-09-16 17:24 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/domain/model/ContractForm.java
> +	@NotNull(message = "想定始業時間を入力してください")
https://qiita.com/suema0331/items/dd91d21168080b747c8d
記事を見て見たりしたのですが
@NotBlanckと@DateTimeFormatでは動作できません。
なので@NotNullで実装したのですが、どのように検索すると出てくるでしょうか。

2022-09-17 05:22 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/domain/model/ContractForm.java
> +	@NotNull(message = "想定始業時間を入力してください")
@NotBlankの場合のエラーはこちらです。
![スクリーンショット (169)](https://user-images.githubusercontent.com/91672424/190841857-793d3a99-1c03-40a3-ac1f-a53f10d959b4.png)

2022-09-28 13:05 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/domain/model/ContractForm.java
> +	@NotNull(message = "想定始業時間を入力してください")
すごいｗ
ちなみに本当にリリースする時はこれもエラーメッセージって表示させるべきなのですか？

2022-09-28 17:49 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/domain/model/ContractForm.java
> +	@NotNull(message = "想定始業時間を入力してください")
リリースする時は、そもそもこういう値が入力できないように入力規制をかけるのが一般的かな。

このスレとは関係ない話になっちゃうと思うけど、皆が成果物として作成している勤怠管理アプリは、残念ながらもっと仕様を詰めないとリリースできないです。
例えば今回設定してないけど、バリデーションで引っかかったメッセージは一文ずつ表示されなければいけないので、`ValidationGroup`を設定する等です。（細かい部分を挙げると沢山あります...）
自分達が実装していた時は気づかなかった部分も、今となっては「バグ起こりそうだな」とか「ここの要件甘いな」とか思ってたりします。（正直直したい...）
今後エンジニアとして仕事をしていくにあたって、この成果物を見直した時に違和感を感じられる様になれば、エンジニアとして成長してるって言えると思う👌

2022-09-28 17:58 UTC, ShizukaKurosawa approved these changes

2022-09-28 17:59 UTC, merged