signupの修正
yushi0620honda/-Deliverables pull request #52
Opened 2022-09-23 05:46 UTC by yushi0620honda

## プルリク前　確認内容
- [ ] インデントがずれていないか
- [ ] コンフリクトが起きてないか
- [ ] 動作確認をしているか
- [ ] チケットの仕様を満たしているか
- [ ] レイアウトは仕様通りか
- [ ] Diff view　縦横確認したか
- [ ] ブランチ名は正しいか

2022-09-28 16:15 UTC, ShizukaKurosawa requested changes

2022-09-28 16:15 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/controller/SignupController.java
>  		return "redirect:/login";
`redirect`していますが、`redirect`にしている理由を教えてください。

2022-09-28 16:15 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/domain/model/SignupForm.java
>  	@AssertTrue(message = "同じものを入力してください")
コメントを修正してください。

2022-09-29 13:45 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/domain/model/SignupForm.java
>  	@AssertTrue(message = "同じものを入力してください")
修正しました。
ありがとうございます。

2022-09-29 17:58 UTC, ShizukaKurosawa requested changes

2022-09-29 17:58 UTC, ShizukaKurosawa commented on src/main/java/com/example/demo/login/domain/model/SignupForm.java
>  	@AssertTrue(message = "同じものを入力してください")
言い方悪かったね笑
エラーメッセージとして「同じものを入力してください」は不適切のため、修正してください。
（パスワードの変更機能でも同じ様なことを記載したと思います。）

2022-09-30 16:22 UTC, yushi0620honda commented on src/main/java/com/example/demo/login/domain/model/SignupForm.java
>  	@AssertTrue(message = "同じものを入力してください")
すみません、勘違いしておりました。
修正したので確認お願いします。

2022-10-03 17:34 UTC, ShizukaKurosawa approved these changes

2022-10-03 17:35 UTC, merged